# Generated by Django 2.2.9 on 2021-03-06 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210306_1452'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='group',
            table='Groups',
        ),
        migrations.AlterModelTable(
            name='post',
            table='Posts',
        ),
    ]
