# Generated by Django 2.2.6 on 2021-04-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20210409_1147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
